version: '3.7'
services:
  spectura:
    environment:
      "DECAP_URL": "http://decap:4531"
      "USE_SIGNATURES": "false"
      "SIGNING_SECRET": "secret"
      "SIGNING_KEY": "key"
      "SIGNING_UNIQUE_NAME": "jix_spectura"
      "BG_RATE_LIMIT_TIME": "10s"
    volumes:
      - "./templates:/templates"
    depends_on:
      - decap
    build:
      context: .
    ports:
      - 8080:19165

  decap:
    image: jobindex/decap:0.12.1
    expose:
      - 4531 # expose to spectura but not to host system
