//Code generated by Decap (`./spectura_typegen.awk | gofmt`). DO NOT EDIT.

package decap

type Result struct {
	Err      []string   `json:"err"`
	Out      [][]string `json:"out"`
	TabID    string     `json:"tab_id"`
	WindowID string     `json:"window_id"`
}

type QueryBlock struct {
	Actions []Action `json:"actions"`
	Repeat  *int     `json:"repeat"`
	While   *Action  `json:"while"`
}

type Request struct {
	Query            []*QueryBlock `json:"query"`
	EmulateViewport  []string      `json:"emulate_viewport"`
	ForwardUserAgent bool          `json:"forward_user_agent"`
	RenderDelay      string        `json:"global_render_delay"`
	ReuseTab         bool          `json:"reuse_tab"`
	ReuseWindow      bool          `json:"reuse_window"`
	SessionID        string        `json:"sessionid"`
	Timeout          string        `json:"timeout"`
}

type Action []string
