name: Build and push to dockerhub

on:
  push:
    tags:
      - '*.*'
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: jobindex
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Tag image with version
        id: meta
        uses: docker/metadata-action@v4
        with:
          # don't push `dev` to :latest
          flavor: "latest=${{ github.ref != 'refs/tags/dev' }}"
          images: jobindex/${{ github.event.repository.name }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
